UPDATE Worlds SET [EstimatedNumCities] = 8 WHERE [ID] = 0;
UPDATE Worlds SET [EstimatedNumCities] = 16 WHERE [ID] = 1;
UPDATE Worlds SET [EstimatedNumCities] = 23 WHERE [ID] = 2;
UPDATE Worlds SET [EstimatedNumCities] = 31 WHERE [ID] = 3;
UPDATE Worlds SET [EstimatedNumCities] = 48 WHERE [ID] = 4;
UPDATE Worlds SET [EstimatedNumCities] = 79 WHERE [ID] = 5;
UPDATE Defines SET [Value] = -10 WHERE [Name] = 'WARMONGER_THREAT_PER_TURN_DECAY';

UPDATE Defines SET [Value] = 20 WHERE [Name] = 'OPINION_WEIGHT_DENOUNCED_ME_FRIENDS';
UPDATE Defines SET [Value] = 20 WHERE [Name] = 'OPINION_WEIGHT_DENOUNCED_ME';
UPDATE Defines SET [Value] = 20 WHERE [Name] = 'OPINION_WEIGHT_DENOUNCED_THEM';
UPDATE Defines SET [Value] = 10 WHERE [Name] = 'OPINION_WEIGHT_DENOUNCED_FRIEND_EACH';
UPDATE Defines SET [Value] = 10 WHERE [Name] = 'OPINION_WEIGHT_DENOUNCED_FRIEND';
UPDATE Defines SET [Value] = 10 WHERE [Name] = 'OPINION_WEIGHT_DENOUNCED_BY_FRIEND_EACH';
UPDATE Defines SET [Value] = 25 WHERE [Name] = 'OPINION_WEIGHT_WAR_FRIEND_EACH';
UPDATE Defines SET [Value] = 45 WHERE [Name] = 'OPINION_WEIGHT_WAR_ME_FRIENDS';

UPDATE Defines SET [Value] = -20 WHERE [Name] = 'OPINION_WEIGHT_LIBERATED_ONE_CITY';
UPDATE Defines SET [Value] = -40 WHERE [Name] = 'OPINION_WEIGHT_LIBERATED_TWO_CITIES';
UPDATE Defines SET [Value] = -60 WHERE [Name] = 'OPINION_WEIGHT_LIBERATED_THREE_CITIES';
UPDATE Defines SET [Value] = -50 WHERE [Name] = 'OPINION_WEIGHT_LIBERATED_CITY';
UPDATE Defines SET [Value] = -100 WHERE [Name] = 'OPINION_WEIGHT_LIBERATED_CAPITAL';
UPDATE Defines SET [Value] = 60 WHERE [Name] = 'OPINION_WEIGHT_CAPTURED_CAPITAL';


